### ISSUE TITLE
Não é possível restaurar backup do Biblivre 5 no Linux

### ISSUE THREAD

**Issue by cleydyr** [cleydyr/Biblivre-5#5]
### Ambiente
Sistema operacional
Linux parallels-vm 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Java
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

Tomcat 7
Package: tomcat7
Architecture: all
Version: 7.0.68-1ubuntu0.1

### Passos para reproduzir
1. Administração > Manutenção
2. Clique em "Ir para a tela de restauração e manutenção" e confirme na janela que aparece
3. Escolha um arquivo de backup válido do Biblivre 5.
4. Clique em "Restaurar backup selecionado" e confirme na janela que aparece

### Resultado esperado
O backup é restaurado com sucesso.

### Resultado atual
A restauração do backup falha e o seguinte erro pode ser visto nos logs:

```
Não foi possível restaurar o backup selecionado
biblivre.core.exceptions.DAOException: java.lang.Exception: Invalid Delegating Connection
	at biblivre.digitalmedia.DigitalMediaDAO.importFile(DigitalMediaDAO.java:139)
	at biblivre.administration.backup.RestoreBO.processMediaRestoreFolder(RestoreBO.java:724)
	at biblivre.administration.backup.RestoreBO.restoreBackup(RestoreBO.java:346)
	at biblivre.administration.backup.RestoreBO.restore(RestoreBO.java:152)
	at biblivre.administration.setup.Handler.restore(Handler.java:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at biblivre.core.controllers.Controller.processRequest(Controller.java:148)
	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:158)
	at biblivre.core.controllers.SchemaServlet.processDynamicRequest(SchemaServlet.java:125)
	at biblivre.core.controllers.SchemaServlet.doPost(SchemaServlet.java:121)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at biblivre.core.controllers.ExtendedRequestResponseFilter.doFilter(ExtendedRequestResponseFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Invalid Delegating Connection
	at biblivre.digitalmedia.DigitalMediaDAO.importFile(DigitalMediaDAO.java:116)
	... 37 more
```

**Comment by cleydyr** [comment]
Não é um bug. O problema foi que a biblioteca do driver do PostgreSQL estava tanto no classpath global do Tomcat quanto do classpath da aplicação.
